import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FollowBar from "@/Components/FollowBar";
import Header from "@/Components/Header";
import Sidebar from "@/Components/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FollowBar/>
        {children}
        <Sidebar/>
        <Header/>
      </body>
    </html>
  );
}
